### ISSUE TITLE
Thank you for valuable work!

### ISSUE THREAD

**Issue by JudePark96** [zhiyuanhubj/ProToD#1]
Hi! appreciate your valuable work!

If you don't mind, would you tell me when the code will be released??

**Comment by zhiyuanhubj** [comment]
Hello, thanks for your interest and sorry for the delay. This work is still under review and I current supplement more experiments. I will strive to release it in March. BTW, my code is based on previous work([Directional-Stimulus-Prompting](https://github.com/Leezekun/Directional-Stimulus-Prompting)), and you can also refer to this.

**Comment by JudePark96** [comment]
Thanks! looking forward to your further work 👍 !
