### ISSUE TITLE
Thank you for your valuable work! Would you like to release the code and prompts in your paper?

### ISSUE THREAD

**Issue by styanXDU** [zhiyuanhubj/ProToD#2]

**Comment by zhiyuanhubj** [comment]
Hello, thanks for your interest and sorry for the delay. This work is still under review and I current supplement more experiments. I will strive to release it in March. BTW, my code is based on previous work([Directional-Stimulus-Prompting](https://github.com/Leezekun/Directional-Stimulus-Prompting)), and you can also refer to this.

**Comment by styanXDU** [comment]
> Hello, thanks for your interest and sorry for the delay. This work is still under review and I current supplement more experiments. I will strive to release it in March. BTW, my code is based on previous work([Directional-Stimulus-Prompting](https://github.com/Leezekun/Directional-Stimulus-Prompting)), and you can also refer to this.

Thanks a lot! looking forward to your further research!
